language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

install: skip

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build -x test --scan'

notifications:
  email:
    recipients:
      - dddalang4@naver.com