language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

before_script: cat /home/travis/.npm/_logs/2021-05-23T06_50_59_795Z-debug.log


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build'

notifications:
  email:
    recipients:
      - dddalang4@naver.com