language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

install: skip

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build -x test --scan'

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/movie-review-app-spring.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: movie-review-app-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: movie-review-app-build
    key: movie-review-app-spring.zip
    bundle_type: zip
    application: movie-review-app-spring
    deployment-group: movie-review-app-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - dddalang4@naver.com