language: java
jdk:
  - openjdk11

branches:
  only:
    - master

before_install:
  - chmod +x ./gradlew

install: "./gradlew clean build -x test --scan yes"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: './gradlew clean build -x test'

notifications:
  email:
    recipients:
      - dddalang4@naver.com